import csv
import random

# Extended base dataset: add more unique query-response pairs (mixing Hindi and English)
# Extended unique base_rows list (query, response) in Hinglish
base_rows = [
    ("Which government schemes support organic farming?", "The Paramparagat Krishi Vikas Yojana (PKVY) promotes organic farming in India."),
    ("Soybean me maximum yield ke liye kaunsa seed best hai?", "JS-335 aur NRC-37 best varieties hain."),
    ("Chickpeas ke beej treatment me kya use karein?", "Rhizobium aur Trichoderma se seed treatment karein."),
    ("What is the ideal pH level for cotton farming?", "The ideal soil pH for cotton farming ranges between 6.0 and 7.5."),
    ("How to make organic compost at home?", "Kitchen waste, cow dung, and dry leaves can be decomposed to make organic compost."),
    ("Agroforestry ka kya fayda hai?", "Agroforestry se soil erosion kam hota hai aur biodiversity badhti hai."),
    ("Cotton farming ke liye drip irrigation best hai ya sprinkler?", "Drip irrigation cotton farming ke liye best hai."),
    ("Drought-prone areas me kaunse crops best hain?", "Millets jaise bajra aur jowar best hain."),
    ("What are the benefits of vermicomposting?", "Vermicomposting enriches soil with essential nutrients and improves moisture retention."),
    ("What is the eligibility for crop insurance in India?", "All registered farmers growing notified crops are eligible for PMFBY crop insurance."),
    ("Gobhi me caterpillar se bachne ke liye kya karein?", "Neem oil aur Bt spray ka use karein."),
    ("Tractor ke liye government subsidy kaise milegi?", "State agriculture department ke online portal se apply karein."),
    ("Chickpea me pod borer ka control kaise karein?", "Neem oil aur Bacillus thuringiensis ka spray karein."),
    ("Which pulses are best suited for dryland farming?", "Chickpea, pigeon pea, and moth bean are ideal for dryland farming."),
    ("What is the impact of excessive nitrogen fertilizers on soil?", "Excessive nitrogen fertilizers soil ko acidic bana dete hain aur nutrient imbalance kar dete hain."),
    ("How to control aphids in mustard crops?", "Using neem oil spray aur ladybugs as biological control aphids ko manage karte hain."),
    ("Soil fertility badhane ke liye best organic manure kaunsa hai?", "Vermicompost aur green manure se soil fertility badhati hai."),
    ("Which biological pesticides are effective for fruit crops?", "Bacillus thuringiensis (Bt) aur neem-based pesticides effective hain."),
    ("Organic farming ke liye kaunsa fertilizer best hai?", "Compost, vermicompost, aur farmyard manure best hain."),
    ("How can farmers use rainwater harvesting for irrigation?", "Farmers rainwater ko farm ponds me store karke dry periods me use kar sakte hain."),
    ("What are the best preventive measures for wheat rust?", "Rust-resistant wheat varieties ugayein aur fungicides timely apply karein."),
    ("Climate change se farming par kya asar padta hai?", "Climate change se monsoon irregular ho sakta hai aur pest infestation badh sakti hai."),
    ("Zero tillage farming ka fayda kya hai?", "Zero tillage se soil structure intact rehta hai aur water retention badhta hai."),
    ("How to prevent soil erosion in hilly agricultural land?", "Contour plowing aur terracing se soil erosion effectively roka ja sakta hai."),
    ("How to increase sugarcane yield using intercropping?", "Sugarcane ke saath legumes jaise cowpea ugane se yield enhance hoti hai."),
    ("How can farmers get loans under the Kisan Credit Card scheme?", "Farmers cooperative banks se land proof aur Aadhaar ke saath apply kar sakte hain."),
    ("What are the symptoms of fungal infections in tomatoes?", "Tomatoes me wilting, yellow spots, aur moldy growth fungal infection ke signs hain."),
    ("Kheti me AI aur drone ka use kaise hota hai?", "AI se crop health analysis aur drone se field monitoring aur spraying hoti hai."),
    ("Organic farming ke liye sarkari subsidy kaise milegi?", "PKVY yojana ke under organic farming subsidy available hai."),
    ("What is the recommended fertilizer dose for high-yield wheat?", "120 kg Nitrogen, 60 kg Phosphorus, aur 40 kg Potassium per hectare ideal dose hai."),
    ("Punjab me wheat ki beejai ka best time kya hai?", "Punjab me wheat ki beejai November ke pehle half me best hoti hai."),
    ("Ganna ki kheti ke liye sabse acchi variety kaunsi hai?", "Co-0238 aur Co-0118 sugarcane ke liye best varieties hain."),
    ("Neem cake ka upyog kis liye hota hai?", "Neem cake se soil fertility badhati hai aur pest control me madad milti hai."),
    ("Sandy soil me paani retention kaise badhayein?", "Organic matter aur mulch ka istemal karke paani retention improve hota hai."),
    ("Which biofertilizers are effective for soybean farming?", "Rhizobium aur Azotobacter soybean ke liye beneficial biofertilizers hain."),
    ("Hybrid seeds aur desi seeds me kya difference hai?", "Hybrid seeds zyada yield dete hain, par desi seeds pest-resistant hote hain."),
    ("Hydroponics farming me paani ka consumption kitna hota hai?", "Hydroponics farming me paani consumption lagbhag 90% kam hota hai."),
    ("Drip irrigation ka use kahan zyada hota hai?", "Drip irrigation Rajasthan aur Gujarat jaise dry areas me zyada hota hai."),
    ("Krishi input subsidy ke liye apply kaise karein?", "Local agriculture office ya PM-KISAN portal se subsidy ke liye apply karein."),
    ("Cotton me pink bollworm ka control kaise karein?", "BT cotton seeds aur pheromone traps se pink bollworm control hota hai."),
    ("How to apply for subsidies on farm equipment in India?", "Farmers PM Kisan Portal ke through equipment subsidies ke liye apply kar sakte hain."),
    ("Mango orchard me fruit fly kaise control karein?", "Pheromone traps aur neem-based spray se fruit fly control hota hai."),
    ("How to manage whitefly infestations in cotton farming?", "Yellow sticky traps aur predatory wasps release karke whitefly control hota hai."),
    ("Mitti ka pH level balance karne ke liye kya karein?", "Lime ya sulphur ka istemal karke soil pH balance kiya jata hai."),
    ("Smart irrigation system kaise kaam karta hai?", "Smart sensors soil moisture detect karte hain aur automated irrigation chalaate hain."),
    ("How to prevent lodging in rice fields?", "Proper nitrogen management aur plant spacing se lodging prevent hoti hai."),
    ("Climate smart agriculture ka matlab kya hai?", "Aise farming methods jo climate change ke risks ko kam karte hain."),
    ("Rice field me stem borer ka control kaise karein?", "Neem oil spray aur pheromone traps se stem borer control hota hai."),
    ("Aquaponics aur hydroponics me kya fark hai?", "Aquaponics me fish farming mix hoti hai, jabki hydroponics me sirf paani aur nutrients use hote hain."),
    ("What are the benefits of the PM Kisan Samman Nidhi scheme?", "PM Kisan se farmers ko ₹6,000 per year direct financial support milta hai."),
    ("Kisan drone ka use kahan hota hai?", "Drones se field monitoring aur pesticide spraying ki jati hai."),
    ("Basmati rice ki kheti ke liye best season kaunsa hai?", "Basmati rice ki kheti June se July me shuru hoti hai."),
    ("Rajasthan me rainwater harvesting ke liye best technique kaunsi hai?", "Khadeen aur johad techniques se rainwater harvesting hoti hai."),
    ("Tomato me fungal disease kaise roke?", "Copper fungicide aur neem extract spray se fungal disease control hoti hai."),
    ("Solar pump se paani kaise supply karein?", "Solar pump ke saath drip ya sprinkler irrigation use hota hai."),
    ("Paddy farming ke liye best fertilizer kaunsa hai?", "DAP aur urea ka mix paddy farming ke liye effective hai."),
    ("What are the best wheat varieties for cultivation in North India?", "HD 2967 aur PBW 343 North India ke liye high-yield wheat varieties hain."),
    ("Bajra ki kheti ke liye sabse accha time kaunsa hai?", "Bajra ki kheti July-August me best hoti hai."),
    ("Rice farming me water requirement kitna hota hai?", "Ek hectare rice farming me lagbhag 5000 liter paani chahiye hota hai."),
    ("Foliar spray fertilizers ka use kyon karein?", "Foliar spray se nutrients directly leaves me absorb hote hain."),
    ("Tomato ki kheti ke liye best soil type kya hai?", "Tomato ke liye loamy aur well-drained soil best hoti hai."),
    ("How to prevent waterlogging in paddy fields?", "Field leveling aur proper drainage se waterlogging roka jata hai."),
    ("Himachal Pradesh me apple farming ke liye best soil kaunsi hai?", "Himachal me apple farming ke liye loamy soil ideal hai."),
    ("Dhaniya ki fasal ko fungal infection se kaise bachayein?", "Sulphur-based fungicide ka spray dhaniya me use karein."),
    ("Soil testing kaise kiya jata hai?", "Soil sample lab me dekar ya testing kit se khud test karein."),
    ("PM Kisan Samman Nidhi Yojana ka paisa kab milta hai?", "PM Kisan ka paisa har 4 mahine me installment me milta hai."),
    ("Bajra ki kheti me paani ki kitni zaroorat hoti hai?", "Bajra low water requirement wala crop hai, kam paani me bhi ug jata hai."),
    ("How does drip irrigation help in water conservation?", "Drip irrigation se evaporation kam hoti hai aur water directly roots tak jata hai."),
    ("Mushroom farming me sabse jyada profit kaunse type me hota hai?", "Button aur Oyster mushroom ka market demand high hota hai."),
    ("What is the best way to irrigate mango orchards?", "Micro-sprinkler irrigation se mango orchards uniformly water hote hain."),
    ("Rainwater harvesting kaise karein?", "Farm ponds aur check dams se rainwater harvesting ki jati hai."),
    ("Which cover crops improve soil structure the most?", "Leguminous cover crops jaise clover aur alfalfa soil structure enhance karte hain."),
    ("Soybean ke liye best irrigation method kya hai?", "Soybean ke liye drip irrigation sabse efficient hai."),
    ("PM Fasal Bima Yojana ka labh kaise uthayein?", "Fasal beejai ke 10 din ke andar policy purchase karein."),
    ("Mustard ki fasal me aphid ka control kaise karein?", "Neem oil aur ladybird beetle se aphid control hota hai."),
    ("Aloo me late blight kaise control karein?", "Bordeaux mixture aur copper fungicide se late blight control hota hai."),
    ("Polyhouse farming ka cost kitna hota hai?", "1 acre polyhouse farming ka cost ₹30-50 lakh hota hai."),
    ("How to improve soil fertility using organic methods?", "Compost, green manure, aur crop rotation se soil fertility improve hoti hai."),
    ("What is the best irrigation method for small farms?", "Small farms ke liye drip irrigation highly efficient hai."),
    ("Gobhi me maximum production ke liye kya karein?", "Proper spacing aur timely irrigation gobhi production badhate hain."),
    ("Kisan mandi me apni fasal ka behtar daam kaise milega?", "Daily mandi rate check karein aur local buyers se negotiate karein."),
    ("What is the best season for maize cultivation in Bihar?", "Maize ke liye Kharif season (June-September) ideal hai."),
    ("Hydroponics aur traditional farming me kya difference hai?", "Hydroponics me bina soil ke paani aur nutrients se plants ugte hain."),
    ("What are the benefits of green manure in farming?", "Green manure se soil fertility aur structure improve hoti hai."),
    ("Acidic soil ke liye kaunsa fertilizer best hai?", "Dolomite lime acidic soil ke pH ko balance karta hai."),
    ("Crop rotation se soil health kaise improve hoti hai?", "Crop rotation se nutrients recycle hote hain aur soil diseases kam hoti hain."),
    ("How to control pests in vegetable farming?", "Integrated pest management aur organic sprays vegetables me use karein."),
    ("What are the benefits of intercropping?", "Intercropping se pest control, soil fertility aur overall yield improve hoti hai."),
    ("How to manage weeds in organic farming?", "Manual weeding aur mulching se organic farming me weeds control hote hain."),
    ("Which organic pesticides are safe for use?", "Neem oil, garlic extract, aur pyrethrum safe organic pesticides hain."),
    ("How to improve irrigation efficiency?", "Regular maintenance aur smart irrigation systems se efficiency badhayi ja sakti hai."),
    ("What role do biofertilizers play in farming?", "Biofertilizers soil microorganisms ko boost karke plant growth enhance karte hain."),
    ("How to achieve sustainable farming practices?", "Organic inputs, crop rotation, aur integrated pest management sustainable farming ke pillars hain."),
    ("What is the role of micro-irrigation in water conservation?", "Micro-irrigation se water wastage bahut kam hota hai."),
    ("How to monitor soil moisture effectively?", "Soil moisture sensors aur regular field checks se monitor karein."),
    ("What techniques can improve seed germination?", "Seed priming aur proper sowing depth se germination improve hoti hai."),
    ("How to manage post-harvest losses?", "Proper storage, timely processing, aur cold chain management se losses kam karein."),
    ("What is the importance of crop diversification?", "Crop diversification se risk spread hota hai aur market fluctuations manage hote hain."),
    ("How to effectively use cover crops?", "Cover crops se soil erosion aur nutrient loss ko prevent karein."),
    ("What is integrated nutrient management?", "Chemical fertilizers ke saath organic manure aur biofertilizers ka combination integrated nutrient management kehlaata hai."),
    ("How to enhance crop resilience to pests?", "Resistant varieties aur biocontrol agents se crop resilience improve hoti hai."),
    ("What are the benefits of conservation agriculture?", "Minimal tillage, residue retention, aur crop rotation conservation agriculture ke benefits hain."),
    ("How to optimize fertilizer application?", "Soil testing aur balanced nutrient management se fertilizer use optimize hota hai."),
    ("What are the best practices for sustainable irrigation?", "Drip irrigation, mulching, aur scheduling sustainable irrigation ke practices hain."),
    ("How to reduce dependency on chemical pesticides?", "Organic methods, biopesticides, aur cultural practices se chemical dependency kam hoti hai."),
    ("What is precision farming?", "Precision farming me technology ka use karke site-specific crop management ki jati hai."),
    ("How to leverage modern agri-tech in farming?", "Drones, sensors, aur data analytics se modern agri-tech ka use hota hai."),
    ("How to ensure quality seed production?", "Certified seeds, proper storage, aur seed treatment quality ensure karte hain."),
    ("What are the challenges of organic farming?", "Pest control, cost, aur market access organic farming ke challenges hain."),
    ("How to improve water use efficiency in arid regions?", "Drip irrigation aur mulching arid regions me water use efficiency improve karte hain."),
    ("What practices help in soil carbon sequestration?", "Crop rotation, cover crops, aur reduced tillage soil carbon sequester karte hain."),
    ("How to adopt climate-resilient agriculture?", "Drought-resistant varieties aur adaptive management climate resilience build karte hain."),
    ("What is the role of precision irrigation?", "Precision irrigation se water wastage kam hota hai aur crop yield optimize hoti hai."),
    ("How to promote sustainable crop production?", "Organic inputs, efficient irrigation, aur integrated pest management sustainable production promote karte hain."),
    ("What strategies reduce soil degradation?", "Crop rotation, organic amendments, aur conservation tillage soil degradation reduce karte hain."),
    ("How to manage nutrient leaching?", "Proper fertilizer application aur cover crops nutrient leaching control karte hain."),
    ("What are the benefits of using organic mulches?", "Organic mulches se soil moisture retain hoti hai aur weed suppression hota hai."),
    ("How to improve crop water productivity?", "Efficient irrigation scheduling aur drought-tolerant varieties water productivity badhate hain."),
    ("What role does biochar play in agriculture?", "Biochar soil fertility improve karta hai aur greenhouse gases reduce karta hai."),
    ("How to implement integrated pest management (IPM)?", "IPM me biological control, cultural practices, aur minimal chemical use shamil hain."),
    ("What techniques reduce post-harvest spoilage?", "Cold storage, proper packaging, aur timely market access spoilage reduce karte hain."),
    ("How to maintain soil structure in intensive farming?", "Crop rotation aur minimal tillage intensive farming me soil structure maintain karte hain."),
    ("What methods improve the efficiency of organic inputs?", "Composting, vermicomposting, aur biofertilizers organic input efficiency badhate hain."),
    ("How to balance crop nutrition?", "Soil testing aur balanced fertilizer application se crop nutrition balance hoti hai."),
    ("What are the benefits of precision agriculture?", "Precision agriculture se input cost kam aur yield maximize hota hai."),
    ("How to monitor crop health remotely?", "Drones, satellites, aur remote sensors se crop health monitor ki jati hai."),
    ("What is the role of data analytics in modern farming?", "Data analytics se decision-making improve hoti hai aur resources optimize hote hain."),
    ("How to reduce the environmental impact of farming?", "Sustainable practices, organic inputs, aur efficient water use farming ka impact reduce karte hain."),
    ("What is the importance of farmer training programs?", "Training programs se farmers ko latest techniques aur practices sikhayi jati hain."),
    ("How to integrate traditional and modern farming methods?", "Traditional wisdom aur modern technology ka combination integrated farming ke liye accha hai."),
    ("What are the benefits of contract farming?", "Contract farming se market access aur risk sharing improve hota hai."),
    ("How to access government schemes for farming?", "Local agriculture offices aur online portals government schemes ke liye information dete hain."),
    ("What measures reduce crop losses during transport?", "Proper packaging, cold storage, aur logistics management crop losses reduce karte hain."),
    ("How to ensure traceability in food production?", "Certification, record-keeping, aur modern tracking systems traceability ensure karte hain."),
    ("What are the benefits of farm mechanization?", "Mechanization se labor cost kam aur efficiency badhti hai."),
    ("How to overcome challenges in small-scale farming?", "Cooperative farming aur government support small-scale farming challenges address karte hain."),
    ("What role does crop insurance play?", "Crop insurance se natural calamities ke loss se farmers protect hote hain."),
    ("How to promote sustainable livestock integration?", "Integrated farming me livestock aur crop production ek saath sustainable hote hain."),
    ("What is the significance of soil organic carbon?", "Soil organic carbon se soil fertility aur structure improve hoti hai."),
    ("How to implement conservation tillage?", "Minimal tillage aur residue retention conservation tillage ke key components hain."),
    ("What are the benefits of on-farm water storage?", "On-farm water storage se irrigation reliability aur drought resilience badhti hai."),
    ("How to optimize energy use in farming operations?", "Energy-efficient machinery aur renewable energy sources energy use optimize karte hain."),
    ("What strategies improve farm profitability?", "Efficient resource management, market access, aur value addition profitability badhate hain."),
    ("How to adapt to fluctuating market prices?", "Diversification aur direct marketing se market price fluctuations manage hote hain."),
    ("What role does agri-tourism play in rural development?", "Agri-tourism se additional income aur community development hoti hai."),
    ("How to effectively market farm produce?", "Branding, direct sales, aur online marketing farm produce ko effectively market karte hain."),
    ("What practices ensure food safety on farms?", "Good agricultural practices (GAP) aur hygiene protocols food safety ensure karte hain."),
    ("How to manage labor shortages in agriculture?", "Mechanization, training, aur migrant labor strategies labor shortages manage karte hain."),
    ("What is the role of cooperatives in farming?", "Cooperatives se collective bargaining aur resource sharing improve hota hai."),
    ("How to increase the shelf life of perishable produce?", "Cold storage, proper packaging, aur timely distribution shelf life badhate hain."),
    ("What measures can reduce pesticide residues?", "Organic farming aur integrated pest management pesticide residues reduce karte hain."),
    ("How to promote local produce in markets?", "Farmers' markets, certification, aur community-supported agriculture local produce promote karte hain."),
    ("What innovations are shaping the future of farming?", "Agri-tech, AI, aur precision agriculture future farming ko redefine kar rahe hain."),
    ("How to transition from conventional to organic farming?", "Gradual conversion, certification, aur training transition me madad karte hain."),
    ("What are the challenges of climate change for farmers?", "Unpredictable weather, pest outbreaks, aur water scarcity climate change challenges hain."),
    ("How to build resilience against extreme weather?", "Drought-resistant varieties, efficient irrigation, aur crop insurance extreme weather se protect karte hain."),
    ("What is the significance of soil health cards?", "Soil health cards se nutrient management aur fertilizer application optimize hoti hai."),
    ("How to improve irrigation scheduling?", "Soil moisture sensors aur automated systems se irrigation scheduling improve hoti hai."),
    ("What are the benefits of precision nutrient management?", "Precision nutrient management se fertilizer wastage kam aur yield maximize hota hai."),
    ("How to reduce greenhouse gas emissions in farming?", "Organic practices aur renewable energy sources greenhouse gases reduce karte hain."),
    ("What is the role of cover crops in erosion control?", "Cover crops se soil erosion aur nutrient loss prevent hota hai."),
    ("How to effectively manage farm waste?", "Composting, recycling, aur proper disposal farm waste manage karte hain."),
    ("What strategies improve water harvesting?", "Contour bunding, check dams, aur farm ponds water harvesting strategies hain."),
    ("How to enhance the quality of farm produce?", "Good agricultural practices aur post-harvest management produce quality enhance karte hain."),
    ("What is the importance of soil biodiversity?", "Soil biodiversity se nutrient cycling aur plant health improve hoti hai."),
    ("How to utilize marginal lands effectively?", "Sustainable practices aur suitable crop selection marginal lands use optimize karte hain."),
    ("What is the role of government in agricultural innovation?", "Government funding, training, aur research se agri-innovation promote hota hai."),
    ("How to integrate renewable energy in farming?", "Solar panels aur wind energy farms renewable energy integrate karte hain."),
    ("What are the benefits of digital farming platforms?", "Digital platforms se market access, data analytics, aur resource optimization hota hai."),
    ("How to manage farm risks effectively?", "Crop diversification, insurance, aur risk management strategies farm risks mitigate karte hain."),
    ("What role do agri-startups play in modern farming?", "Agri-startups innovative solutions aur technology adoption drive karte hain."),
    ("How to improve farmer income through value addition?", "Processing, packaging, aur branding se farmer income badh sakti hai."),
    ("What is contract farming and its benefits?", "Contract farming se farmers fixed prices aur assured market paate hain."),
    ("How to ensure transparency in farm supply chains?", "Blockchain aur certification se supply chain transparency ensure hoti hai."),
    ("What are the environmental benefits of sustainable farming?", "Sustainable farming se soil health, water conservation, aur biodiversity protect hoti hai."),
    ("How to promote farmer cooperatives effectively?", "Training, policy support, aur community engagement cooperatives promote karte hain."),
    ("What role does microfinance play in rural agriculture?", "Microfinance small farmers ko credit aur financial support provide karta hai."),
    ("How to address post-harvest losses in agriculture?", "Cold storage, timely processing, aur infrastructure improvements post-harvest losses reduce karte hain."),
    ("What measures support agri-export growth?", "Quality standards, government incentives, aur market linkages agri-export boost karte hain."),
    ("How to leverage social media for farm marketing?", "Social media se direct consumer engagement aur branding opportunities milti hain."),
    ("What are the key challenges in organic certification?", "Cost, transition period, aur market acceptance organic certification challenges hain."),
    ("How to promote sustainable aquaculture?", "Integrated fish farming, water recycling, aur organic feed sustainable aquaculture promote karte hain."),
    ("What innovations are emerging in precision livestock farming?", "IoT, sensors, aur data analytics precision livestock farming me innovations la rahe hain."),
    ("How to effectively manage fodder crops?", "Timely harvesting, balanced fertilizer, aur proper storage fodder crop management me madad karte hain."),
    ("What is the role of genetic improvement in crop yield?", "Improved varieties aur hybridization genetic improvement se yield boost karte hain."),
    ("How to ensure quality control in seed production?", "Certified seeds, rigorous testing, aur proper storage quality control ensure karte hain."),
    ("What are the benefits of integrated farming systems?", "Integrated systems livestock, crops, aur fisheries combine karke efficiency badhate hain."),
    ("How to adopt climate-resilient farming techniques?", "Drought-resistant varieties, efficient irrigation, aur crop insurance se climate resilience build hoti hai."),
    ("What is the role of precision agriculture in resource optimization?", "Precision agriculture se inputs accurately apply hote hain aur resource wastage kam hota hai."),
    ("How to use remote sensing for crop monitoring?", "Satellites aur drones remote sensing se crop health aur stress monitor karte hain."),
    ("What are the benefits of using farm management software?", "Software se record-keeping, decision making, aur planning improve hoti hai."),
    ("How to enhance farm productivity with modern techniques?", "Mechanization, digital tools, aur training se farm productivity boost hoti hai."),
    ("What strategies can help reduce operational costs in farming?", "Efficient resource use, cooperative purchasing, aur renewable energy operational costs reduce karte hain."),
    ("How to create a sustainable farm business model?", "Diversification, value addition, aur market linkages sustainable business model build karte hain."),
    ("What is the importance of soil moisture conservation?", "Soil moisture conservation se irrigation needs aur crop stress reduce hote hain."),
    ("How to utilize farm residues effectively?", "Residues se composting aur bioenergy production sustainable practices hain."),
    ("What are the advantages of direct marketing for farmers?", "Direct marketing se higher margins aur consumer engagement hoti hai."),
    ("How to ensure financial sustainability in agriculture?", "Diversified income, risk management, aur government schemes financial sustainability promote karte hain.")
]


def generate_unique_dataset(base_rows, total_lines, output_file):
    """
    Generates a CSV file with unique query-response pairs.
    
    Each generated row appends a unique reference number to ensure overall uniqueness.
    
    :param base_rows: List of base (query, response) tuples.
    :param total_lines: Total number of lines to generate.
    :param output_file: Output CSV file name.
    """
    # Remove any accidental duplicates from base_rows
    unique_base = list({(q.strip(), a.strip()) for q, a in base_rows})
    
    generated = set()
    with open(output_file, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(["query", "response"])
        
        count = 0
        while count < total_lines:
            # Randomly choose one base pair
            q, a = random.choice(unique_base)
            # Append a unique reference to each field so the final row is unique
            new_q = f"{q} [Ref #{count+1}]"
            new_a = f"{a} (Detail ID: {count+1})"
            # Check if this exact combination is already generated
            if (new_q, new_a) not in generated:
                writer.writerow([new_q, new_a])
                generated.add((new_q, new_a))
                count += 1

    print(f"Dataset saved as {output_file} with {total_lines} unique lines.")

# Generate a CSV file with 500 unique query-response pairs
total_lines = 5000
output_file = "unique_agriculture_dataset_500.csv"
generate_unique_dataset(base_rows, total_lines, output_file)
